In [24]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split


In [3]:
dataset=pd.read_csv(r"C:\Users\User\Desktop\iris.csv")

In [4]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
X=dataset.iloc[:,:-1].values

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y=dataset.iloc[:,4].values

In [8]:
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [10]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2)

In [11]:
scaler=StandardScaler()

In [12]:
scaler

StandardScaler()

In [13]:
scaler.fit(X_train)

StandardScaler()

In [14]:
X_train=scaler.transform(X_train)

In [15]:
X_train

array([[-1.16877538, -1.32264211,  0.38828125,  0.62198796],
       [ 1.00756499,  0.59249579,  1.07014102,  1.6732352 ],
       [-0.3224208 , -0.12568092,  0.38828125,  0.35917614],
       [ 0.0403026 ,  0.35310355,  0.55874619,  0.75339386],
       [ 1.12847278, -0.12568092,  0.95649772,  1.14761158],
       [-0.56423639,  2.0288492 , -1.43001145, -1.08628882],
       [ 0.76574939, -0.12568092,  1.12696266,  1.27901749],
       [ 2.21664297,  1.78945697,  1.63835748,  1.27901749],
       [ 0.1612104 , -2.04081882,  0.10417302, -0.29785339],
       [-1.16877538, -0.12568092, -1.3731898 , -1.34910064],
       [ 0.40302599,  0.83188802,  0.89967608,  1.41042339],
       [-1.28968318,  0.83188802, -1.08908156, -1.34910064],
       [-0.92695979,  0.59249579, -1.20272486, -0.95488292],
       [ 0.64484159, -0.84385763,  0.84285443,  0.88479977],
       [ 0.52393379,  0.59249579,  0.50192455,  0.49058205],
       [-0.92695979,  1.78945697, -1.31636815, -1.21769473],
       [ 1.24938058,  0.

In [16]:
X_test=scaler.transform(X_test)

In [17]:
X_test

array([[ 0.2821182 , -0.12568092,  0.61556784,  0.75339386],
       [-1.04786759, -1.80142658, -0.29357851, -0.29785339],
       [-1.77331437,  0.35310355, -1.43001145, -1.34910064],
       [-0.80605199,  0.83188802, -1.3731898 , -1.34910064],
       [ 1.37028838,  0.35310355,  0.50192455,  0.22777024],
       [ 0.2821182 , -0.36507316,  0.50192455,  0.22777024],
       [-0.44332859, -1.56203434, -0.06629192, -0.29785339],
       [ 0.64484159, -0.6044654 ,  1.01331937,  1.27901749],
       [ 2.45845857,  1.78945697,  1.46789254,  1.01620567],
       [-1.28968318, -0.12568092, -1.3731898 , -1.48050654],
       [-1.04786759,  0.83188802, -1.25954651, -1.08628882],
       [ 0.76574939, -0.12568092,  0.95649772,  0.75339386],
       [ 0.52393379,  0.83188802,  1.01331937,  1.5418293 ],
       [-1.16877538, -1.56203434, -0.29357851, -0.29785339],
       [ 1.00756499,  0.59249579,  1.07014102,  1.14761158],
       [-0.201513  ,  3.22581039, -1.31636815, -1.08628882],
       [-0.92695979,  1.

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [30]:
y_pred=classifier.predict(X_test)

In [31]:
y_pred

array(['virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'virginica', 'setosa',
       'setosa', 'virginica', 'virginica', 'versicolor', 'virginica',
       'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'setosa', 'versicolor', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'versicolor', 'virginica'], dtype=object)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix

In [33]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.83      0.91        12
   virginica       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.95      0.93      0.93        30

[[11  0  0]
 [ 0 10  2]
 [ 0  0  7]]
